// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    url: process.env["process.env.PORT"] as string,
  },
  datasource: {
    url: process.env["process.env.PORT"] as string,
  },
  
});
